"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ExternalLink, ShieldCheck, Cpu, Database, Flame, Clock } from "lucide-react";

const GithubIcon = (props: React.SVGProps<SVGSVGElement>) => (
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}>
    <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
    <path d="M9 18c-4.51 2-5-2-7-2" />
  </svg>
);

interface Project {
  title: string;
  category: string;
  problem: string;
  solution: string;
  tech: string[];
  challenges: string;
  impact: string;
  github: string;
  demo?: string;
  badge?: string;
  icon: React.ComponentType<any>;
}

const projects: Project[] = [
  {
    title: "LuminAI — AI Career Mentor",
    category: "LLM / Full-Stack Platform",
    problem: "Job seekers lack personalized mock interview practice, ATS review feedback, and structured skills roadmaps.",
    solution: "A unified portal providing ATS resume analysis, real-time AI mock interviews, custom roadmap generators, and chat mentoring.",
    tech: ["Gemini API", "React", "Next.js", "TypeScript", "Node.js", "Express", "JWT", "Vercel", "Render"],
    challenges: "Parsing complex PDF layouts and scaling LLM prompts to produce consistent structured JSON roadmaps.",
    impact: "Provides instant ATS matching scores, interactive mock feedback, and secures user data via JWT authentication.",
    github: "https://github.com/ajinkyaXhub",
    demo: "https://github.com/ajinkyaXhub",
    icon: ShieldCheck,
  },
  {
    title: "ContextBot — RAG Document Q&A",
    category: "Retrieval Augmented Generation",
    problem: "Searching across huge volumes of multi-format documentation is slow and yields hallucinated replies.",
    solution: "A production-grade RAG pipeline using ChromaDB vector store, Hugging Face embeddings, and Groq Llama 3.3 for high-accuracy semantic search.",
    tech: ["ChromaDB", "Hugging Face", "Groq Llama 3.3", "Python", "React", "Tesseract OCR", "PyPDF2"],
    challenges: "Aligning text chunk size with overlap ratios to achieve 92% retrieval accuracy, and reducing vector memory consumption.",
    impact: "Features drag-and-drop document upload, real-time OCR support, and streaming markdown answers with source citations.",
    github: "https://github.com/ajinkyaXhub",
    icon: Database,
  },
  {
    title: "FitGenie — AI Nutrition & Fitness",
    category: "Vision AI / Personal Health",
    problem: "Calorie logging is tedious, and custom workout plans generated by personal trainers are expensive.",
    solution: "An automated assistant that generates meal plans and 7-day workouts, analyzing plate photos using vision models.",
    tech: ["LLMs", "Vision AI", "React", "Node.js", "MongoDB", "TailwindCSS", "Express"],
    challenges: "Mapping image labels to accurate macronutrient estimates and synchronizing workout demonstration guides.",
    impact: "Over 500+ custom plans generated with dynamic visual macronutrient dashboards and persistent MongoDB profiles.",
    github: "https://github.com/ajinkyaXhub",
    demo: "https://github.com/ajinkyaXhub",
    icon: Flame,
  },
  {
    title: "XAI Model Monitoring Platform",
    category: "Explainable AI / MLOps",
    problem: "ML models are black boxes, and explaining decision logic or detecting data drift in production is extremely difficult.",
    solution: "An MLOps dashboard showing real-time data drift alerts, feature contribution scores, and local model explanations.",
    tech: ["Python", "Flask", "React", "Scikit-Learn", "SHAP", "LIME", "Docker"],
    challenges: "Streaming high-compute SHAP force plots to client browsers asynchronously without clogging flask thread locks.",
    impact: "Translates model bias metrics and prediction contributions into readable charts for non-technical stakeholders.",
    github: "https://github.com/ajinkyaXhub",
    badge: "Currently Building",
    icon: Clock,
  },
];

export default function Projects() {
  const [selectedIdx, setSelectedIdx] = useState<number | null>(null);

  return (
    <section id="projects" className="py-24 relative overflow-hidden">
      <div className="max-w-7xl mx-auto px-6">
        {/* Section Header */}
        <div className="flex flex-col md:flex-row md:items-end justify-between mb-16 gap-4">
          <div>
            <span className="font-mono text-xs uppercase tracking-[0.2em] text-primary">03 / Works</span>
            <h2 className="text-3xl sm:text-4xl font-extrabold text-white mt-2">AI & Web applications</h2>
          </div>
          <div className="h-[1px] flex-grow bg-white/10 hidden md:block mx-12 mb-4" />
        </div>

        {/* Projects Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {projects.map((proj, idx) => {
            const Icon = proj.icon;
            return (
              <motion.div
                layoutId={`card-container-${idx}`}
                onClick={() => setSelectedIdx(idx)}
                key={proj.title}
                className="glass-card p-8 cursor-pointer flex flex-col justify-between min-h-[350px] relative group overflow-hidden border border-white/5 hover:border-primary/20 hover:shadow-[0_0_30px_rgba(0,242,254,0.05)]"
                whileHover={{ y: -4 }}
              >
                {/* Accent Blob */}
                <div className="absolute top-0 right-0 w-24 h-24 bg-primary/5 rounded-full blur-2xl group-hover:bg-primary/10 transition-colors" />

                <div>
                  <div className="flex justify-between items-start mb-6">
                    <div className="p-3 bg-zinc-900 border border-white/5 rounded-lg text-primary">
                      <Icon className="w-6 h-6" />
                    </div>
                    {proj.badge ? (
                      <span className="px-3 py-1 text-[10px] font-bold uppercase tracking-wider bg-purple-500/10 border border-purple-500/25 text-purple-400 rounded-full flex items-center gap-1.5 animate-pulse">
                        <span className="w-1.5 h-1.5 rounded-full bg-purple-400" />
                        {proj.badge}
                      </span>
                    ) : (
                      <span className="text-[10px] font-mono font-semibold uppercase text-zinc-500 tracking-wider">
                        {proj.category}
                      </span>
                    )}
                  </div>

                  <h3 className="text-2xl font-bold text-white mb-3 group-hover:text-primary transition-colors">
                    {proj.title}
                  </h3>
                  <p className="text-zinc-400 text-sm line-clamp-3 leading-relaxed mb-6">
                    {proj.solution}
                  </p>
                </div>

                <div>
                  {/* Tech tags preview */}
                  <div className="flex flex-wrap gap-1.5 mb-4">
                    {proj.tech.slice(0, 4).map((t) => (
                      <span key={t} className="text-[10px] font-mono font-semibold px-2 py-0.5 bg-zinc-900 border border-white/5 text-zinc-400 rounded">
                        {t}
                      </span>
                    ))}
                    {proj.tech.length > 4 && (
                      <span className="text-[10px] font-mono font-semibold px-2 py-0.5 bg-zinc-900 border border-white/5 text-zinc-500 rounded">
                        +{proj.tech.length - 4} more
                      </span>
                    )}
                  </div>

                  <span className="text-xs font-mono font-bold tracking-wider text-primary group-hover:underline flex items-center gap-1">
                    Analyze Project Details →
                  </span>
                </div>
              </motion.div>
            );
          })}
        </div>

        {/* Details Overlay / Modal */}
        <AnimatePresence>
          {selectedIdx !== null && (
            <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
              {/* Backdrop */}
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                onClick={() => setSelectedIdx(null)}
                className="absolute inset-0 bg-[#030303]/80 backdrop-blur-md cursor-zoom-out"
              />

              {/* Modal Container */}
              <motion.div
                layoutId={`card-container-${selectedIdx}`}
                className="glass-card max-w-2xl w-full p-8 relative overflow-y-auto max-h-[85vh] z-10 border border-white/10"
              >
                {/* Header */}
                <div className="flex justify-between items-start mb-6">
                  <div>
                    <span className="text-xs font-mono font-semibold uppercase tracking-wider text-primary">
                      {projects[selectedIdx].category}
                    </span>
                    <h3 className="text-2xl sm:text-3xl font-extrabold text-white mt-1">
                      {projects[selectedIdx].title}
                    </h3>
                  </div>
                  <button
                    onClick={() => setSelectedIdx(null)}
                    className="p-1 rounded-full bg-white/5 hover:bg-white/10 text-zinc-400 hover:text-white transition-colors"
                  >
                    ✕
                  </button>
                </div>

                <div className="space-y-6 text-sm text-zinc-300">
                  {/* Problem & Solution */}
                  <div className="space-y-2">
                    <h4 className="text-xs font-mono uppercase text-zinc-400 tracking-wider font-semibold">The Problem</h4>
                    <p className="leading-relaxed bg-zinc-950 p-4 rounded-lg border border-white/5">
                      {projects[selectedIdx].problem}
                    </p>
                  </div>

                  <div className="space-y-2">
                    <h4 className="text-xs font-mono uppercase text-zinc-400 tracking-wider font-semibold">The Solution</h4>
                    <p className="leading-relaxed bg-zinc-950 p-4 rounded-lg border border-white/5 text-white">
                      {projects[selectedIdx].solution}
                    </p>
                  </div>

                  {/* Challenges & Impact */}
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    <div className="space-y-1.5">
                      <h4 className="text-xs font-mono uppercase text-zinc-400 tracking-wider font-semibold">Engineering Challenge</h4>
                      <p className="leading-relaxed text-zinc-300">
                        {projects[selectedIdx].challenges}
                      </p>
                    </div>
                    <div className="space-y-1.5">
                      <h4 className="text-xs font-mono uppercase text-zinc-400 tracking-wider font-semibold">Business Impact</h4>
                      <p className="leading-relaxed text-zinc-300">
                        {projects[selectedIdx].impact}
                      </p>
                    </div>
                  </div>

                  {/* Tech stack */}
                  <div className="space-y-2">
                    <h4 className="text-xs font-mono uppercase text-zinc-400 tracking-wider font-semibold">Full Technology Stack</h4>
                    <div className="flex flex-wrap gap-2">
                      {projects[selectedIdx].tech.map((t) => (
                        <span key={t} className="text-xs font-mono px-3 py-1 bg-zinc-900 border border-white/5 text-zinc-200 rounded">
                          {t}
                        </span>
                      ))}
                    </div>
                  </div>
                </div>

                {/* Actions Footer */}
                <div className="flex gap-4 border-t border-white/5 mt-8 pt-6">
                  <a
                    href={projects[selectedIdx].github}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="flex-1 flex items-center justify-center gap-2 py-3 bg-white/5 hover:bg-white/10 text-white border border-white/10 rounded-md text-xs uppercase tracking-wider font-bold font-mono transition-all"
                  >
                    <GithubIcon className="w-4 h-4" /> View Source
                  </a>
                  {projects[selectedIdx].demo && (
                    <a
                      href={projects[selectedIdx].demo}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="flex-1 flex items-center justify-center gap-2 py-3 bg-primary hover:bg-[#00d4e8] text-[#030303] rounded-md text-xs uppercase tracking-wider font-bold font-mono transition-all"
                    >
                      <ExternalLink className="w-4 h-4" /> Live Demo
                    </a>
                  )}
                </div>
              </motion.div>
            </div>
          )}
        </AnimatePresence>
      </div>
    </section>
  );
}
