"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ExternalLink, ShieldCheck, Cpu, Database, Flame, Clock, MessageSquare, Home, Heart, Key, DollarSign, Music } from "lucide-react";
import TiltCard from "./TiltCard";

const GithubIcon = (props: React.SVGProps<SVGSVGElement>) => (
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}>
    <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
    <path d="M9 18c-4.51 2-5-2-7-2" />
  </svg>
);

interface Project {
  title: string;
  category: string;
  tab: "ai" | "fullstack";
  problem: string;
  solution: string;
  tech: string[];
  challenges: string;
  impact: string;
  github: string;
  demo?: string;
  badge?: string;
  icon: React.ComponentType<any>;
}

const projects: Project[] = [
  {
    title: "LuminAI — AI Career Mentor",
    category: "LLM / Full-Stack Platform",
    tab: "ai",
    problem: "Job seekers lack personalized mock interview practice, ATS review feedback, and structured skills roadmaps.",
    solution: "A unified portal providing ATS resume analysis, real-time AI mock interviews, custom roadmap generators, and chat mentoring.",
    tech: ["Gemini API", "React", "Next.js", "TypeScript", "Node.js", "Express", "JWT", "Vercel", "Render"],
    challenges: "Parsing complex PDF layouts and scaling LLM prompts to produce consistent structured JSON roadmaps.",
    impact: "Provides instant ATS matching scores, interactive mock feedback, and secures user data via JWT authentication.",
    github: "https://github.com/ajinkyaXhub",
    demo: "https://github.com/ajinkyaXhub",
    icon: ShieldCheck,
  },
  {
    title: "ContextBot — RAG Document Q&A",
    category: "Retrieval Augmented Generation",
    tab: "ai",
    problem: "Searching across huge volumes of multi-format documentation is slow and yields hallucinated replies.",
    solution: "A production-grade RAG pipeline using ChromaDB vector store, Hugging Face embeddings, and Groq Llama 3.3 for high-accuracy semantic search.",
    tech: ["ChromaDB", "Hugging Face", "Groq Llama 3.3", "Python", "React", "Tesseract OCR", "PyPDF2"],
    challenges: "Aligning text chunk size with overlap ratios to achieve 92% retrieval accuracy, and reducing vector memory consumption.",
    impact: "Features drag-and-drop document upload, real-time OCR support, and streaming markdown answers with source citations.",
    github: "https://github.com/ajinkyaXhub",
    icon: Database,
  },
  {
    title: "FitGenie — AI Nutrition & Fitness",
    category: "Vision AI / Personal Health",
    tab: "ai",
    problem: "Calorie logging is tedious, and custom workout plans generated by personal trainers are expensive.",
    solution: "An automated assistant that generates meal plans and 7-day workouts, analyzing plate photos using vision models.",
    tech: ["LLMs", "Vision AI", "React", "Node.js", "MongoDB", "TailwindCSS", "Express"],
    challenges: "Mapping image labels to accurate macronutrient estimates and synchronizing workout demonstration guides.",
    impact: "Over 500+ custom plans generated with dynamic visual macronutrient dashboards and persistent MongoDB profiles.",
    github: "https://github.com/ajinkyaXhub",
    demo: "https://github.com/ajinkyaXhub",
    icon: Flame,
  },
  {
    title: "XAI Model Monitoring Platform",
    category: "Explainable AI / MLOps",
    tab: "ai",
    problem: "ML models are black boxes, and explaining decision logic or detecting data drift in production is extremely difficult.",
    solution: "An MLOps dashboard showing real-time data drift alerts, feature contribution scores, and local model explanations.",
    tech: ["Python", "Flask", "React", "Scikit-Learn", "SHAP", "LIME", "Docker"],
    challenges: "Streaming high-compute SHAP force plots to client browsers asynchronously without clogging flask thread locks.",
    impact: "Translates model bias metrics and prediction contributions into readable charts for non-technical stakeholders.",
    github: "https://github.com/ajinkyaXhub",
    badge: "Currently Building",
    icon: Clock,
  },
  {
    title: "Alfred — Voice Assistant",
    category: "Voice AI / Automation",
    tab: "ai",
    problem: "Hard to configure custom system workflows and execute voice automation via traditional visual layouts.",
    solution: "A J.A.R.V.I.S.-inspired virtual assistant capable of executing system tasks and custom voice actions.",
    tech: ["Python", "NLP", "Voice AI", "SpeechRecognition", "Pyttsx3"],
    challenges: "Reducing latency on speech-to-text recognition under noisy environmental conditions.",
    impact: "Allows hands-free automation of repetitive tasks and applications on local workstation environments.",
    github: "https://github.com/ajinkyaXhub",
    icon: MessageSquare,
  },
  {
    title: "Multi-Device Home Management",
    category: "IoT / Realtime Sync",
    tab: "fullstack",
    problem: "Integrating various home automation devices results in sync latency and offline data drops.",
    solution: "Cloud-based home management featuring real-time database sync and multi-device command routing.",
    tech: ["IoT", "Supabase", "Cloud Databases", "PostgreSQL", "Realtime WebSockets"],
    challenges: "Handling rapid write state syncs and ensuring database connections do not exhaust during load surges.",
    impact: "Zero-latency synchronization of light states and thermostat configurations across simultaneous clients.",
    github: "https://github.com/ajinkyaXhub",
    icon: Home,
  },
  {
    title: "NGO Site Management",
    category: "Full-Stack Portal",
    tab: "fullstack",
    problem: "NGO operations require frequent site content updates and donor list management without web developer dependencies.",
    solution: "Dual-module NGO platform featuring a secure Admin Dashboard to edit and broadcast live organizational updates.",
    tech: ["React", "Node.js", "Express", "MongoDB", "TailwindCSS"],
    challenges: "Designing secure access paths for non-technical admins while maintaining high public route response times.",
    impact: "Allows administrative workers to record donation metrics and edit program cards dynamically.",
    github: "https://github.com/ajinkyaXhub",
    icon: Heart,
  },
  {
    title: "User Auth using Streamlit",
    category: "Security Portal",
    tab: "fullstack",
    problem: "Securing prototype python dashboards quickly requires complex custom auth structures.",
    solution: "A drop-in streamlit session validator featuring secure registration and login schemas.",
    tech: ["Python", "Streamlit", "SQLite", "BCrypt Session Hashing"],
    challenges: "Persisting logged-in sessions securely without standard cookie management in Streamlit's redraw model.",
    impact: "Provides rapid authentication wrapping for visual ML/analytics prototype views.",
    github: "https://github.com/ajinkyaXhub",
    demo: "https://useralogiandregis.streamlit.app/",
    icon: Key,
  },
  {
    title: "PennyWise — Expense Tracker",
    category: "Finance Tracker",
    tab: "fullstack",
    problem: "Manual monthly budget tracking leads to tracking leaks and unclear balance breakdowns.",
    solution: "Expense application featuring real-time balance sheets, categories, and automated budget threshold overrides.",
    tech: ["HTML/CSS/JS", "Node.js", "Express", "MongoDB"],
    challenges: "Designing clean database aggregations for nested categories with rapid insertion schedules.",
    impact: "Helps users identify leaks, contributing to an average 15% budget saving index for test users.",
    github: "https://github.com/ajjumane/PennyWise---Expence-Tracker",
    demo: "https://penny-wise-expence-tracker.vercel.app/",
    icon: DollarSign,
  },
  {
    title: "Moodify — Mood Matcher",
    category: "Java API Integration",
    tab: "fullstack",
    problem: "Streaming music databases lack dynamic sentiment indexing for playlist recommendations.",
    solution: "An API-integrated web application suggesting tracks matching real-time user sentiments and activities.",
    tech: ["Java", "React", "TypeScript", "Spotify API", "Spring Boot"],
    challenges: "Mapping categorical user mood tokens to numerical Spotify feature matrices (valence, energy).",
    impact: "Offers highly personalized, single-click playlist routing directly into active Spotify profiles.",
    github: "https://github.com/ajjumane/Moodify",
    demo: "https://moodifyaj.vercel.app/",
    icon: Music,
  },
];

export default function Projects() {
  const [activeTab, setActiveTab] = useState<"all" | "ai" | "fullstack">("all");
  const [selectedIdx, setSelectedIdx] = useState<number | null>(null);

  const filteredProjects = projects.filter(
    (proj) => activeTab === "all" || proj.tab === activeTab
  );

  return (
    <section id="projects" className="py-24 relative overflow-hidden">
      <div className="max-w-7xl mx-auto px-6">
        {/* Section Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="flex flex-col md:flex-row md:items-end justify-between mb-16 gap-4"
        >
          <div>
            <span className="font-mono text-xs uppercase tracking-[0.2em] text-[#00d4e8]">03 / Works</span>
            <h2 className="text-4xl font-extrabold text-white mt-2">Projects Portfolios</h2>
          </div>
          {/* Tabs Filter */}
          <div className="flex items-center gap-2 bg-[#080d1a] border border-white/5 rounded-lg p-1">
            {(["all", "ai", "fullstack"] as const).map((tab) => (
              <button
                key={tab}
                onClick={() => setActiveTab(tab)}
                className={`px-4 py-1.5 rounded text-xs font-mono font-bold uppercase transition-all ${
                  activeTab === tab
                    ? "bg-[#00d4e8] text-[#050810]"
                    : "text-zinc-400 hover:text-white"
                }`}
              >
                {tab === "ai" ? "AI & ML" : tab === "fullstack" ? "Full-Stack" : "All"}
              </button>
            ))}
          </div>
        </motion.div>

        {/* Projects Grid */}
        <motion.div
          layout
          className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6"
        >
          <AnimatePresence mode="popLayout">
            {filteredProjects.map((proj, idx) => {
              const mainIdx = projects.findIndex((p) => p.title === proj.title);
              const Icon = proj.icon;
              return (
                <motion.div
                  layout
                  initial={{ opacity: 0, y: 50 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true, margin: "-100px" }}
                  transition={{ type: "spring", stiffness: 80, delay: (idx % 3) * 0.1 }}
                  onClick={() => setSelectedIdx(mainIdx)}
                  key={proj.title}
                  className="h-full"
                >
                  <TiltCard className="h-full rounded-2xl">
                    <div className="glass p-6 rounded-2xl border border-white/5 hover:border-[#00d4e8]/20 hover:bg-white/[0.01] transition-all flex flex-col justify-between h-full relative group overflow-hidden">
                      <div className="absolute top-0 right-0 w-24 h-24 bg-[#00d4e8]/5 rounded-full blur-2xl group-hover:bg-[#00d4e8]/10 transition-colors" />

                      <div>
                        <div className="flex justify-between items-start mb-6">
                          <div className="p-3 bg-zinc-950 border border-white/5 rounded-lg text-[#00d4e8]">
                            <Icon className="w-5 h-5" />
                          </div>
                          {proj.badge ? (
                            <span className="px-2.5 py-0.5 text-[9px] font-bold uppercase tracking-wider bg-purple-500/10 border border-purple-500/25 text-purple-400 rounded-full flex items-center gap-1.5 animate-pulse">
                              <span className="w-1.5 h-1.5 rounded-full bg-purple-400" />
                              {proj.badge}
                            </span>
                          ) : (
                            <span className="text-[9px] font-mono font-semibold uppercase text-zinc-500 tracking-wider">
                              {proj.category}
                            </span>
                          )}
                        </div>

                        <h3 className="text-xl font-bold text-white mb-2 group-hover:text-[#00d4e8] transition-colors line-clamp-1">
                          {proj.title}
                        </h3>
                        <p className="text-zinc-400 text-xs leading-relaxed line-clamp-3 mb-6">
                          {proj.solution}
                        </p>
                      </div>

                      <div>
                        <div className="flex flex-wrap gap-1.5 mb-4">
                          {proj.tech.slice(0, 3).map((t) => (
                            <span key={t} className="text-[9px] font-mono font-semibold px-2 py-0.5 bg-zinc-950 border border-white/5 text-zinc-400 rounded">
                              {t}
                            </span>
                          ))}
                          {proj.tech.length > 3 && (
                            <span className="text-[9px] font-mono font-semibold px-2 py-0.5 bg-zinc-950 border border-white/5 text-zinc-500 rounded">
                              +{proj.tech.length - 3}
                            </span>
                          )}
                        </div>

                        <span className="text-xs font-mono font-bold tracking-wider text-[#00d4e8] group-hover:underline flex items-center gap-1">
                          Analyze Details →
                        </span>
                      </div>
                    </div>
                  </TiltCard>
                </motion.div>
              );
            })}
          </AnimatePresence>
        </motion.div>

        {/* Detailed Modal Overlay */}
        <AnimatePresence>
          {selectedIdx !== null && (
            <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                onClick={() => setSelectedIdx(null)}
                className="absolute inset-0 bg-[#050810]/80 backdrop-blur-md cursor-zoom-out"
              />

              <motion.div
                initial={{ opacity: 0, scale: 0.95, y: 20 }}
                animate={{ opacity: 1, scale: 1, y: 0 }}
                exit={{ opacity: 0, scale: 0.95, y: 20 }}
                className="glass-card max-w-2xl w-full p-8 relative overflow-y-auto max-h-[85vh] z-10 border border-white/10"
              >
                {/* Header */}
                <div className="flex justify-between items-start mb-6">
                  <div>
                    <span className="text-xs font-mono font-semibold uppercase tracking-wider text-[#00d4e8]">
                      {projects[selectedIdx].category}
                    </span>
                    <h3 className="text-2xl sm:text-3xl font-extrabold text-white mt-1">
                      {projects[selectedIdx].title}
                    </h3>
                  </div>
                  <button
                    onClick={() => setSelectedIdx(null)}
                    className="p-1 rounded-full bg-white/5 hover:bg-white/10 text-zinc-400 hover:text-white transition-colors"
                  >
                    ✕
                  </button>
                </div>

                <div className="space-y-6 text-sm text-zinc-300">
                  <div className="space-y-2">
                    <h4 className="text-xs font-mono uppercase text-zinc-400 tracking-wider font-semibold">The Problem</h4>
                    <p className="leading-relaxed bg-zinc-950 p-4 rounded-lg border border-white/5">
                      {projects[selectedIdx].problem}
                    </p>
                  </div>

                  <div className="space-y-2">
                    <h4 className="text-xs font-mono uppercase text-zinc-400 tracking-wider font-semibold">The Solution</h4>
                    <p className="leading-relaxed bg-zinc-950 p-4 rounded-lg border border-white/5 text-white">
                      {projects[selectedIdx].solution}
                    </p>
                  </div>

                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    <div className="space-y-1.5">
                      <h4 className="text-xs font-mono uppercase text-zinc-400 tracking-wider font-semibold">Engineering Challenge</h4>
                      <p className="leading-relaxed text-zinc-300">
                        {projects[selectedIdx].challenges}
                      </p>
                    </div>
                    <div className="space-y-1.5">
                      <h4 className="text-xs font-mono uppercase text-zinc-400 tracking-wider font-semibold">Business Impact</h4>
                      <p className="leading-relaxed text-zinc-300">
                        {projects[selectedIdx].impact}
                      </p>
                    </div>
                  </div>

                  <div className="space-y-2">
                    <h4 className="text-xs font-mono uppercase text-zinc-400 tracking-wider font-semibold">Full Technology Stack</h4>
                    <div className="flex flex-wrap gap-2">
                      {projects[selectedIdx].tech.map((t) => (
                        <span key={t} className="text-xs font-mono px-3 py-1 bg-zinc-900 border border-white/5 text-zinc-200 rounded">
                          {t}
                        </span>
                      ))}
                    </div>
                  </div>
                </div>

                {/* Actions Footer */}
                <div className="flex gap-4 border-t border-white/5 mt-8 pt-6">
                  <a
                    href={projects[selectedIdx].github}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="flex-1 flex items-center justify-center gap-2 py-3 bg-white/5 hover:bg-white/10 text-white border border-white/10 rounded-md text-xs uppercase tracking-wider font-bold font-mono transition-all"
                  >
                    <GithubIcon className="w-4 h-4" /> View Source
                  </a>
                  {projects[selectedIdx].demo && (
                    <a
                      href={projects[selectedIdx].demo}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="flex-1 flex items-center justify-center gap-2 py-3 bg-[#00d4e8] hover:bg-[#00b8c4] text-[#050810] rounded-md text-xs uppercase tracking-wider font-bold font-mono transition-all"
                    >
                      <ExternalLink className="w-4 h-4" /> Live Demo
                    </a>
                  )}
                </div>
              </motion.div>
            </div>
          )}
        </AnimatePresence>
      </div>
    </section>
  );
}
